### ISSUE TITLE
能否加入聲調顯示？

### ISSUE THREAD

**Issue by laubonghaudoi** [edward-martyr/rime-yahwe_zaonhe#1]
很高興能見到吳語協會版拼音的碼表。希望能加入聲調顯示，不用是連讀變調後的聲調，只用原本的單字調就行，這樣對學習上海話的新手會很有幫助

**Comment by yuanhao-chen-nyoeghau** [comment]
謝謝您的建議，不過上海話的聲調基本都能直接從拼寫中看出來（陽舒、陰入、陽入），剩下的陰平、陰仄之別只需要區分平仄就可以了；初學者可以通過如通過普通話來區分。至於哪些是濁聲母、哪些有喉塞韻尾，只能留給語感或者滬語教程了。

**Comment by laubonghaudoi** [comment]
感謝指導。另外我有個問題，就是readme中gif所用的皮膚配色是什麼呢？能否把配置分享一下？

**Comment by yuanhao-chen-nyoeghau** [comment]
```
preset_color_schemes/greyblue:
    name: "Grey Blue"
    horizontal: false                           # 候选条横向显示
    inline_preedit: true                        # 启用内嵌编码模式，候选条首行不显示拼音
    candidate_format: "%c.\u2005%@\u2005"       # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。
    corner_radius: 6                            # 候选条圆角半径
    border_height: 0                            # 窗口边界高度，大于圆角半径才生效
    border_width: 10                           # 窗口边界宽度，大于圆角半径才生效
    back_color: 0xF6D7B5                        # 候选条背景色
    line_spacing: 5                             # 候选词的行间距
		# spacing: 3                                  # 在非内嵌编码模式下，预编辑和候选词之间的间距
    border_color: 0xE0B693                      # 边框色
    font_face: "PingFangHK-Thin"             # 候选词字体
    font_point: 18                              # 预选栏文字字号
    label_font_face: "MyriadPro-LightSemiCn"       # 候选词编号字体
    label_font_point: 20                        # 预选栏编号字号
    text_color: 0xF7F7F7                        # HEX颜色代码，但是要注意顺序是蓝绿红（倒序）0xBBGGRR
    candidate_text_color: 0x000000              #非第一候选项
    hilited_candidate_back_color: 0xD98840      #第一候选项背景
    hilited_candidate_text_color: 0xFFFFFF      #第一候选项
```
這是當時的方案。
我自己現在用的字體是	`NotoSansCJKkr-Thin`以及[源様ゴシック](https://github.com/ButTaiwan/genyog-font)。
